export const interfaceLanguages = [
  { code: 'en', short: 'EN', label: 'English' },
  { code: 'kk', short: 'ҚАЗ', label: 'Қазақша' },
  { code: 'ru', short: 'РУС', label: 'Русский' },
];

export const appCopy = {
  en: {
    nav: { home: 'Today', discover: 'Song catalog', library: 'My learning', progress: 'Progress', research: 'Research mode' },
    search: 'Search songs, artists or a skill', localLearner: 'Local learner', level: 'Level B1',
    qwenReady: 'Free web AI is configured', qwenOffline: 'Add one OpenRouter key · curated lessons work', analyze: 'Analyze a song',
    homeEyebrow: 'YOUR NEXT ACTION', homeTitle: 'Learn English through songs you already love.', homeSub: 'One focused lesson combines meaning, listening, useful vocabulary, real English and speaking.',
    startFirst: 'Start the first lesson', continueLesson: 'Continue lesson', startLesson: 'Start lesson', restartLesson: 'Practise again', listenHere: 'Listen in SONORA',
    nextStep: 'Next step', activitiesDone: 'activities completed', of: 'of', complete: 'complete',
    wordsSaved: 'Saved words', usefulWords: 'Useful words', activeMinutes: 'Active minutes', firstAccuracy: 'First-attempt accuracy', lessonsDone: 'Lessons completed',
    nothingYet: 'No activity yet', honestStats: 'These numbers come only from your completed actions.',
    weeklyGoal: 'Weekly goal', weeklyEmpty: 'Complete a lesson to begin your week.', reviewDue: 'Words ready to review', reviewNow: 'Start review',
    focusedStages: 'focused stages', planListening: 'Listening with an authorised source', planWords: 'Six words with active recall', planCheckpoint: 'Five-question checkpoint', learningPaths: 'complete learning paths',
    recommended: 'Choose your next song', recommendedSub: 'Every song has a different language focus and a complete learning path.', seeCatalog: 'See full catalog',
    catalogEyebrow: 'CURATED SONG LESSONS', catalogTitle: 'Choose a song with a purpose.', catalogSub: 'Filter by skill, level or classroom suitability. Save a song or start its full lesson.',
    all: 'All', safe: 'Classroom safe', vocabulary: 'Vocabulary', listening: 'Listening', idioms: 'Idioms',
    sortLevel: 'Level: easiest first', sortScore: 'Learning value', sortDuration: 'Shortest first', results: 'lessons found',
    savedSong: 'Saved', saveSong: 'Save song', noSongs: 'No matching songs', clearFilters: 'Clear search',
    learningValue: 'learning value', minutes: 'min', guided: 'Teacher guidance', suitable: 'Classroom suitable', notRecommended: 'Not recommended for class',
    libraryEyebrow: 'YOUR WORKSPACE', libraryTitle: 'Keep, review and return.', librarySub: 'Saved songs and a real word-review queue live here — not another dashboard.',
    wordBank: 'Word bank', savedSongs: 'Saved songs', dueToday: 'due now', noWords: 'Save words during a lesson and they will appear here.',
    wordColumn: 'Word', meaningColumn: 'Meaning', reviewColumn: 'Review', meaningSkill: 'Meaning', realEnglishSkill: 'Real English',
    noSavedSongs: 'Use the bookmark in the catalog to build your collection.', pronounce: 'Hear pronunciation', remove: 'Remove',
    reviewTitle: 'Quick word review', reveal: 'Reveal meaning', again: 'Again', hard: 'Hard', good: 'Good', easy: 'Easy', reviewDone: 'Review complete', close: 'Close',
    progressEyebrow: 'REAL LEARNING DATA', progressTitle: 'Progress without demo numbers.', progressSub: 'Only completed activities, first attempts and active lesson time are counted.',
    skillBreakdown: 'Skill evidence', recentLessons: 'Lesson history', currentLessons: 'In progress', noProgress: 'Start a lesson to create your first progress record.',
    attempts: 'attempts', accuracy: 'accuracy', mastered: 'Mastered', needsReview: 'Needs review', inProgress: 'In progress', completed: 'Completed',
    researchNote: 'Research mode uses clearly labelled synthetic sample data until a real study is imported.', openResearch: 'Open research workspace', backToStudent: 'Back to student mode',
    analyzerTitle: 'Turn a song excerpt into a lesson', analyzerSub: 'MiniMax M3 processes the excerpt through OpenRouter. SONORA does not store the excerpt; OpenRouter and the model provider receive it under their own data terms.',
    artist: 'Artist', songTitle: 'Song title', excerpt: 'Short lyrics excerpt', runAnalysis: 'Analyze with free web AI', analyzing: 'Building the language map…',
    qwenRequired: 'Web AI could not create a lesson right now. Retry later; curated lessons remain fully available.', useLesson: 'Open generated lesson', edit: 'Edit',
    basicEstimate: 'Basic heuristic only · not a CEFR assessment', aiReview: 'AI-generated · teacher review required',
    menu: 'Open navigation', language: 'Interface language',
  },
  kk: {
    nav: { home: 'Бүгін', discover: 'Әндер каталогы', library: 'Менің оқуым', progress: 'Прогресс', research: 'Зерттеу режимі' },
    search: 'Ән, орындаушы немесе дағдыны іздеу', localLearner: 'Жергілікті оқушы', level: 'B1 деңгейі',
    qwenReady: 'Тегін web ЖИ бапталған', qwenOffline: 'Бір OpenRouter кілтін қос · дайын сабақтар жұмыс істейді', analyze: 'Әнді талдау',
    homeEyebrow: 'КЕЛЕСІ ӘРЕКЕТ', homeTitle: 'Өзің ұнататын әндер арқылы ағылшын тілін үйрен.', homeSub: 'Бір толық сабақта мағына, тыңдалым, пайдалы сөздер, шынайы ағылшын және сөйлеу бар.',
    startFirst: 'Алғашқы сабақты бастау', continueLesson: 'Сабақты жалғастыру', startLesson: 'Сабақты бастау', restartLesson: 'Қайта жаттығу', listenHere: 'SONORA ішінде тыңдау',
    nextStep: 'Келесі кезең', activitiesDone: 'әрекет орындалды', of: '/', complete: 'орындалды',
    wordsSaved: 'Сақталған сөз', usefulWords: 'Пайдалы сөздер', activeMinutes: 'Белсенді минут', firstAccuracy: 'Алғашқы талпыныс дәлдігі', lessonsDone: 'Аяқталған сабақ',
    nothingYet: 'Әзірге дерек жоқ', honestStats: 'Бұл сандар тек орындалған әрекеттерден есептеледі.',
    weeklyGoal: 'Апталық мақсат', weeklyEmpty: 'Аптаны бастау үшін бір сабақты аяқта.', reviewDue: 'Қайталауға дайын сөз', reviewNow: 'Қайталауды бастау',
    focusedStages: 'нақты кезең', planListening: 'Рұқсат етілген дереккөзбен тыңдалым', planWords: 'Алты сөзді белсенді еске түсіру', planCheckpoint: 'Бес сұрақтық қорытынды тест', learningPaths: 'толық оқу жолы',
    recommended: 'Келесі әнді таңда', recommendedSub: 'Әр әннің тілдік мақсаты мен толық оқу жолы бөлек.', seeCatalog: 'Толық каталог',
    catalogEyebrow: 'ДАЙЫН ӘН САБАҚТАРЫ', catalogTitle: 'Әнді нақты мақсатпен таңда.', catalogSub: 'Дағды, деңгей және сабаққа сәйкестік бойынша сүз. Әнді сақта немесе толық сабақты баста.',
    all: 'Барлығы', safe: 'Сабаққа жарамды', vocabulary: 'Сөздік қор', listening: 'Тыңдалым', idioms: 'Идиомалар',
    sortLevel: 'Деңгей: жеңілінен', sortScore: 'Оқу құндылығы', sortDuration: 'Қысқасынан', results: 'сабақ табылды',
    savedSong: 'Сақталды', saveSong: 'Әнді сақтау', noSongs: 'Сәйкес ән табылмады', clearFilters: 'Іздеуді тазарту',
    learningValue: 'оқу құндылығы', minutes: 'мин', guided: 'Мұғаліммен', suitable: 'Сабаққа жарамды', notRecommended: 'Сабаққа ұсынылмайды',
    libraryEyebrow: 'СЕНІҢ ЖҰМЫС ОРТАҢ', libraryTitle: 'Сақта, қайтала, жалғастыр.', librarySub: 'Сақталған әндер мен нақты сөз қайталау кезегі осында орналасады.',
    wordBank: 'Сөздер банкі', savedSongs: 'Сақталған әндер', dueToday: 'қазір қайталау керек', noWords: 'Сабақта сөздерді сақта — олар осында шығады.',
    wordColumn: 'Сөз', meaningColumn: 'Мағына', reviewColumn: 'Қайталау', meaningSkill: 'Мағына', realEnglishSkill: 'Шынайы ағылшын',
    noSavedSongs: 'Жинақ құру үшін каталогтағы белгішені бас.', pronounce: 'Айтылуын тыңдау', remove: 'Өшіру',
    reviewTitle: 'Жылдам сөз қайталау', reveal: 'Мағынасын ашу', again: 'Қайта', hard: 'Қиын', good: 'Жақсы', easy: 'Оңай', reviewDone: 'Қайталау аяқталды', close: 'Жабу',
    progressEyebrow: 'НАҚТЫ ОҚУ ДЕРЕГІ', progressTitle: 'Демо сандарсыз прогресс.', progressSub: 'Тек орындалған әрекеттер, алғашқы талпыныстар және белсенді оқу уақыты есептеледі.',
    skillBreakdown: 'Дағды дәлелдері', recentLessons: 'Сабақтар тарихы', currentLessons: 'Жалғасып жатқан', noProgress: 'Алғашқы прогресс жазбасын жасау үшін сабақты баста.',
    attempts: 'талпыныс', accuracy: 'дәлдік', mastered: 'Меңгерілді', needsReview: 'Қайталау керек', inProgress: 'Орындалуда', completed: 'Аяқталды',
    researchNote: 'Нақты зерттеу жүктелгенше, зерттеу режимінде белгіленген синтетикалық үлгі деректер қолданылады.', openResearch: 'Зерттеу ортасын ашу', backToStudent: 'Оқушы режиміне қайту',
    analyzerTitle: 'Ән үзіндісін сабаққа айналдыр', analyzerSub: 'MiniMax M3 үзіндіні OpenRouter арқылы өңдейді. SONORA үзіндіні сақтамайды; OpenRouter мен модель провайдері оны өз ережелері бойынша алады.',
    artist: 'Орындаушы', songTitle: 'Ән атауы', excerpt: 'Қысқа мәтін үзіндісі', runAnalysis: 'Тегін web ЖИ арқылы талдау', analyzing: 'Тіл картасы жасалуда…',
    qwenRequired: 'Web ЖИ қазір жаңа сабақ жасай алмады. Кейін қайталап көр; дайын сабақтар толық жұмыс істейді.', useLesson: 'Жасалған сабақты ашу', edit: 'Өзгерту',
    basicEstimate: 'Қарапайым жуық бағалау · CEFR тесті емес', aiReview: 'ЖИ жасаған · мұғалім тексеруі керек',
    menu: 'Навигацияны ашу', language: 'Интерфейс тілі',
  },
  ru: {
    nav: { home: 'Сегодня', discover: 'Каталог песен', library: 'Моё обучение', progress: 'Прогресс', research: 'Режим исследования' },
    search: 'Поиск песни, исполнителя или навыка', localLearner: 'Локальный ученик', level: 'Уровень B1',
    qwenReady: 'Бесплатный web AI настроен', qwenOffline: 'Добавь один ключ OpenRouter · готовые уроки работают', analyze: 'Разобрать песню',
    homeEyebrow: 'СЛЕДУЮЩЕЕ ДЕЙСТВИЕ', homeTitle: 'Учи английский через песни, которые уже любишь.', homeSub: 'Один содержательный урок объединяет смысл, аудирование, полезные слова, живой английский и говорение.',
    startFirst: 'Начать первый урок', continueLesson: 'Продолжить урок', startLesson: 'Начать урок', restartLesson: 'Пройти ещё раз', listenHere: 'Слушать в SONORA',
    nextStep: 'Следующий этап', activitiesDone: 'действий выполнено', of: 'из', complete: 'готово',
    wordsSaved: 'Слов сохранено', usefulWords: 'Полезных слов', activeMinutes: 'Активных минут', firstAccuracy: 'Точность первых попыток', lessonsDone: 'Уроков завершено',
    nothingYet: 'Пока нет данных', honestStats: 'Эти числа считаются только по выполненным действиям.',
    weeklyGoal: 'Цель на неделю', weeklyEmpty: 'Заверши урок, чтобы начать неделю.', reviewDue: 'Слов пора повторить', reviewNow: 'Начать повторение',
    focusedStages: 'содержательных этапов', planListening: 'Аудирование с разрешённым источником', planWords: 'Шесть слов с активным припоминанием', planCheckpoint: 'Итоговая проверка из пяти вопросов', learningPaths: 'полных учебных маршрутов',
    recommended: 'Выбери следующую песню', recommendedSub: 'У каждой песни — свой языковой фокус и полный учебный маршрут.', seeCatalog: 'Весь каталог',
    catalogEyebrow: 'ПОДГОТОВЛЕННЫЕ УРОКИ', catalogTitle: 'Выбирай песню с конкретной целью.', catalogSub: 'Фильтруй по навыку, уровню и пригодности для класса. Сохрани песню или начни полный урок.',
    all: 'Все', safe: 'Для урока', vocabulary: 'Лексика', listening: 'Аудирование', idioms: 'Идиомы',
    sortLevel: 'Сначала проще', sortScore: 'Учебная ценность', sortDuration: 'Сначала короче', results: 'уроков найдено',
    savedSong: 'Сохранено', saveSong: 'Сохранить песню', noSongs: 'Ничего не найдено', clearFilters: 'Сбросить поиск',
    learningValue: 'учебная ценность', minutes: 'мин', guided: 'С преподавателем', suitable: 'Подходит для урока', notRecommended: 'Не рекомендуется для урока',
    libraryEyebrow: 'ТВОЁ РАБОЧЕЕ МЕСТО', libraryTitle: 'Сохраняй, повторяй, возвращайся.', librarySub: 'Здесь собраны сохранённые песни и настоящая очередь повторения слов — это не ещё один дашборд.',
    wordBank: 'Банк слов', savedSongs: 'Сохранённые песни', dueToday: 'пора повторить', noWords: 'Сохраняй слова во время урока — они появятся здесь.',
    wordColumn: 'Слово', meaningColumn: 'Значение', reviewColumn: 'Повторение', meaningSkill: 'Смысл', realEnglishSkill: 'Живой английский',
    noSavedSongs: 'Нажми закладку в каталоге, чтобы собрать свою коллекцию.', pronounce: 'Прослушать произношение', remove: 'Удалить',
    reviewTitle: 'Быстрое повторение слов', reveal: 'Показать значение', again: 'Снова', hard: 'Трудно', good: 'Хорошо', easy: 'Легко', reviewDone: 'Повторение завершено', close: 'Закрыть',
    progressEyebrow: 'РЕАЛЬНЫЕ ДАННЫЕ ОБУЧЕНИЯ', progressTitle: 'Прогресс без демонстрационных цифр.', progressSub: 'Учитываются только выполненные действия, первые попытки и реальное активное время.',
    skillBreakdown: 'Данные по навыкам', recentLessons: 'История уроков', currentLessons: 'В процессе', noProgress: 'Начни урок, чтобы появилась первая запись прогресса.',
    attempts: 'попыток', accuracy: 'точность', mastered: 'Освоено', needsReview: 'Нужно повторить', inProgress: 'В процессе', completed: 'Завершён',
    researchNote: 'Пока реальное исследование не импортировано, исследовательский режим использует явно отмеченные синтетические данные.', openResearch: 'Открыть исследование', backToStudent: 'Вернуться в режим ученика',
    analyzerTitle: 'Преврати фрагмент песни в урок', analyzerSub: 'MiniMax M3 обрабатывает фрагмент через OpenRouter. SONORA не хранит фрагмент; OpenRouter и провайдер модели получают его по собственным правилам обработки данных.',
    artist: 'Исполнитель', songTitle: 'Название песни', excerpt: 'Короткий фрагмент текста', runAnalysis: 'Проанализировать с бесплатным web AI', analyzing: 'Строим языковую карту…',
    qwenRequired: 'Web AI сейчас не смог создать новый урок. Повтори позже; все подготовленные уроки продолжают работать.', useLesson: 'Открыть созданный урок', edit: 'Изменить',
    basicEstimate: 'Только приблизительная эвристика · не оценка CEFR', aiReview: 'Создано ИИ · нужна проверка учителя',
    menu: 'Открыть навигацию', language: 'Язык интерфейса',
  },
};
