export const languages = [
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'kk', label: 'Қазақша', short: 'ҚАЗ' },
  { code: 'ru', label: 'Русский', short: 'РУС' },
];

export const copy = {
  en: {
    nav: { home: 'Home', discover: 'Discover', library: 'My learning', progress: 'Progress', research: 'Research' },
    hello: 'Good evening, Amina',
    subtitle: 'Ready to turn up your English?',
    streak: '12 day streak',
    search: 'Search a song, artist or skill',
    continue: 'Continue learning',
    resume: 'Resume lesson',
    journey: 'Your rhythm, your progress',
    journeySub: 'You are building real English, one song at a time.',
    words: 'Words learned',
    minutes: 'Minutes listened',
    accuracy: 'Quiz accuracy',
    lessons: 'Lessons completed',
    weekly: 'This week',
    goal: 'Weekly goal',
    goalMeta: '3 of 5 lessons completed',
    recent: 'Fresh from your playlist',
    viewAll: 'View all',
    featured: 'Made for your English',
    featuredSub: 'Lessons matched to your B1 level and music taste.',
    start: 'Start lesson',
    min: 'min',
    exploreTitle: 'Find your next lesson',
    exploreSub: 'Songs you already love, transformed into real English practice.',
    searchShort: 'Search music',
    all: 'All songs',
    safe: 'Classroom safe',
    vocab: 'Vocabulary',
    idioms: 'Idioms',
    listening: 'Listening',
    popular: 'Popular lessons',
    selected: 'lesson selected',
    analyzeSong: 'Analyze your song',
    analyzerTitle: 'Turn any song into a lesson',
    analyzerSub: 'Add a song and a short lyrics excerpt. SONORA will estimate its level, detect useful language and build a learning card.',
    artistLabel: 'Artist',
    songLabel: 'Song title',
    lyricsLabel: 'Lyrics excerpt',
    lyricsHint: 'The excerpt goes only to your configured SONORA AI service and is never stored; a short analysis summary may be saved.',
    runAnalysis: 'Analyze language',
    analyzing: 'Finding useful English…',
    analysisReady: 'Your learning card is ready',
    detectedWords: 'Unique words',
    slangFound: 'Slang found',
    difficulty: 'Difficulty',
    useForLesson: 'Use this lesson',
    libraryTitle: 'My learning',
    librarySub: 'Keep the words and expressions you want to make yours.',
    savedWords: 'Saved words',
    review: 'Review now',
    progressTitle: 'Your English is finding its rhythm',
    progressSub: 'A clear view of what is improving and what to practise next.',
    level: 'Current level',
    strongest: 'Strongest skill',
    focus: 'Next focus',
    skillGrowth: 'Skill growth',
    last30: 'Last 30 days',
    vocabulary: 'Vocabulary',
    comprehension: 'Listening',
    speaking: 'Speaking',
    grammar: 'Grammar',
    back: 'Back',
    lesson: 'Interactive lesson',
    meaning: 'Meaning',
    vocabularyTab: 'Vocabulary',
    languageTab: 'Language lab',
    practice: 'Practice',
    songMeaning: 'What is this song really about?',
    meaningLead: 'A simple explanation — without translating every line.',
    keyIdea: 'The key idea',
    mood: 'Mood & message',
    culture: 'Context that matters',
    learningMap: 'Your learning map',
    usefulWords: 'Useful words',
    expressions: 'Expressions',
    grammarPoints: 'Grammar points',
    understanding: 'Understanding the song',
    continueVocabulary: 'Continue to vocabulary',
    wordsFromSong: 'Words worth keeping',
    wordsSub: 'Understand them here. Use them everywhere.',
    shouldLearn: 'Should I learn this?',
    standard: 'Standard English',
    informal: 'Informal speech',
    slang: 'Slang',
    saveWord: 'Save word',
    saved: 'Saved',
    labTitle: 'How real English works',
    labSub: 'See the difference between song language and classroom English.',
    songForm: 'Song / spoken form',
    classroomForm: 'Standard form',
    why: 'Why artists use it',
    quizTitle: 'Quick meaning check',
    quizSub: 'Choose the meaning that fits the song.',
    check: 'Check answer',
    correct: 'Exactly — you understood the context.',
    retry: 'Almost. Look at the emotional context and try again.',
    finish: 'Finish lesson',
    complete: 'Lesson complete!',
    completeSub: 'You added 8 useful words and one more song to your English journey.',
    speakingTitle: 'Talk about the song',
    speakingPrompt: 'What is the main message of this song, and how does it make you feel?',
    startSpeaking: 'Start speaking',
    stopSpeaking: 'Listening…',
    speechUnsupported: 'Voice recognition is not available in this browser. You can type your answer instead.',
    transcript: 'Your answer',
    speakingFeedback: 'Speaking feedback',
    clarity: 'Clarity',
    vocabularyRange: 'Vocabulary range',
    goHome: 'Back to home',
    score: 'Learning score',
    classroom: 'Classroom fit',
    guided: 'Teacher guidance',
    safeLabel: 'Safe',
    wordsLower: 'words',
    localAiTitle: 'MiniMax M3 · OpenRouter',
    localAiSidebar: 'Free trilingual lesson generation with one web API key.',
    openAnalyzer: 'Open song analyzer',
    localAiReady: 'web AI ready',
    configuredAiReady: 'free web AI ready',
    localAiFallback: 'Web AI is unavailable — basic heuristic estimate only',
    checkingAi: 'Checking web AI configuration…',
    basicLocalAnalysis: 'Basic heuristic · not a CEFR assessment',
    heuristicNotice: 'This fallback is a rough language estimate, not a validated CEFR or safety assessment.',
    aiNeedsReview: 'AI-generated · review required',
    curatedAnalysis: 'Curated learning analysis',
    answerDevelopment: 'Answer development',
    speechPrivacy: 'Optional · voice recognition may use your browser speech service',
    notRecommended: 'Not for class',
    demoData: 'DEMO DATA',
  },
  kk: {
    nav: { home: 'Басты бет', discover: 'Әндер', library: 'Менің оқуым', progress: 'Прогресс', research: 'Зерттеу' },
    hello: 'Қайырлы кеш, Амина',
    subtitle: 'Ағылшын тіліңді жаңа деңгейге көтеруге дайынсың ба?',
    streak: '12 күн қатарынан',
    search: 'Ән, орындаушы немесе дағдыны іздеу',
    continue: 'Оқуды жалғастыр',
    resume: 'Сабақты жалғастыру',
    journey: 'Сенің ырғағың, сенің прогресің',
    journeySub: 'Әр әнмен шынайы ағылшын тіліңді дамытып келесің.',
    words: 'Үйренген сөздер',
    minutes: 'Тыңдалған минут',
    accuracy: 'Тест дәлдігі',
    lessons: 'Аяқталған сабақ',
    weekly: 'Осы апта',
    goal: 'Апталық мақсат',
    goalMeta: '5 сабақтың 3-еуі аяқталды',
    recent: 'Плейлистіңдегі жаңа сабақтар',
    viewAll: 'Барлығын көру',
    featured: 'Саған арналған ағылшын тілі',
    featuredSub: 'B1 деңгейіңе және музыкалық талғамыңа сай сабақтар.',
    start: 'Сабақты бастау',
    min: 'мин',
    exploreTitle: 'Келесі сабағыңды тап',
    exploreSub: 'Өзің жақсы көретін әндер — енді шынайы ағылшын тәжірибесі.',
    searchShort: 'Ән іздеу',
    all: 'Барлық әндер',
    safe: 'Мектепке жарамды',
    vocab: 'Сөздік қор',
    idioms: 'Идиомалар',
    listening: 'Тыңдалым',
    popular: 'Танымал сабақтар',
    selected: 'сабақ таңдалды',
    analyzeSong: 'Өз әніңді талдау',
    analyzerTitle: 'Кез келген әнді сабаққа айналдыр',
    analyzerSub: 'Әнді және мәтіннің қысқа үзіндісін қос. SONORA деңгейін анықтап, пайдалы тілді тауып, оқу картасын жасайды.',
    artistLabel: 'Орындаушы',
    songLabel: 'Ән атауы',
    lyricsLabel: 'Ән мәтінінің үзіндісі',
    lyricsHint: 'Үзінді тек бапталған SONORA ЖИ қызметіне жіберіледі және сақталмайды; қысқа талдау қорытындысы сақталуы мүмкін.',
    runAnalysis: 'Тілді талдау',
    analyzing: 'Пайдалы ағылшын тілін іздеудеміз…',
    analysisReady: 'Оқу картасы дайын',
    detectedWords: 'Бірегей сөз',
    slangFound: 'Табылған сленг',
    difficulty: 'Күрделілік',
    useForLesson: 'Сабақта қолдану',
    libraryTitle: 'Менің оқуым',
    librarySub: 'Қажетті сөздер мен тіркестерді сақтап, қайтала.',
    savedWords: 'Сақталған сөздер',
    review: 'Қайталау',
    progressTitle: 'Ағылшын тілің өз ырғағын тауып келеді',
    progressSub: 'Қай дағдың өсіп жатқанын және нені қайталау керегін көр.',
    level: 'Қазіргі деңгей',
    strongest: 'Мықты дағды',
    focus: 'Келесі мақсат',
    skillGrowth: 'Дағдылардың өсуі',
    last30: 'Соңғы 30 күн',
    vocabulary: 'Сөздік қор',
    comprehension: 'Тыңдалым',
    speaking: 'Сөйлеу',
    grammar: 'Грамматика',
    back: 'Артқа',
    lesson: 'Интерактивті сабақ',
    meaning: 'Мағынасы',
    vocabularyTab: 'Сөздік',
    languageTab: 'Тіл зертханасы',
    practice: 'Жаттығу',
    songMeaning: 'Бұл ән шын мәнінде не туралы?',
    meaningLead: 'Әр жолды аудармай-ақ, түсінікті түрде талдаймыз.',
    keyIdea: 'Негізгі ой',
    mood: 'Көңіл күйі мен идеясы',
    culture: 'Маңызды контекст',
    learningMap: 'Оқу картасы',
    usefulWords: 'Пайдалы сөз',
    expressions: 'Тіркес',
    grammarPoints: 'Грамматикалық тақырып',
    understanding: 'Әнді түсіну',
    continueVocabulary: 'Сөздерге өту',
    wordsFromSong: 'Есте сақтауға тұрарлық сөздер',
    wordsSub: 'Осы жерде түсін. Кез келген жерде қолдан.',
    shouldLearn: 'Бұл сөзді үйрену керек пе?',
    standard: 'Стандартты ағылшын',
    informal: 'Бейресми сөйлеу',
    slang: 'Сленг',
    saveWord: 'Сақтау',
    saved: 'Сақталды',
    labTitle: 'Шынайы ағылшын қалай жұмыс істейді',
    labSub: 'Әндегі және ресми ағылшын тіліндегі айырмашылықты көр.',
    songForm: 'Әндегі / ауызекі нұсқа',
    classroomForm: 'Стандартты нұсқа',
    why: 'Әншілер не үшін қолданады',
    quizTitle: 'Мағынаны тексеру',
    quizSub: 'Ән контексіне сәйкес жауапты таңда.',
    check: 'Жауапты тексеру',
    correct: 'Дұрыс — сен контексті түсіндің.',
    retry: 'Сәл қалды. Эмоциялық контекстке назар аударып, қайталап көр.',
    finish: 'Сабақты аяқтау',
    complete: 'Сабақ аяқталды!',
    completeSub: '8 пайдалы сөз үйреніп, ағылшын жолыңа тағы бір ән қостың.',
    speakingTitle: 'Ән туралы айт',
    speakingPrompt: 'Бұл әннің негізгі ойы қандай және ол саған қандай сезім береді?',
    startSpeaking: 'Сөйлеуді бастау',
    stopSpeaking: 'Тыңдап тұрмыз…',
    speechUnsupported: 'Бұл браузерде дауысты тану жоқ. Жауабыңды мәтінмен жаза аласың.',
    transcript: 'Сенің жауабың',
    speakingFeedback: 'Сөйлеу бойынша пікір',
    clarity: 'Айқындық',
    vocabularyRange: 'Сөздік қоры',
    goHome: 'Басты бетке оралу',
    score: 'Оқу көрсеткіші',
    classroom: 'Сабаққа сәйкестігі',
    guided: 'Мұғаліммен бірге',
    safeLabel: 'Қауіпсіз',
    wordsLower: 'сөз',
    localAiTitle: 'MiniMax M3 · OpenRouter',
    localAiSidebar: 'Бір web API кілтімен үш тілде тегін сабақ жасайды.',
    openAnalyzer: 'Ән талдағышын ашу',
    localAiReady: 'web ЖИ дайын',
    configuredAiReady: 'тегін web ЖИ дайын',
    localAiFallback: 'Web ЖИ қолжетімсіз — тек қарапайым жуық бағалау',
    checkingAi: 'Web ЖИ баптауы тексерілуде…',
    basicLocalAnalysis: 'Қарапайым бағалау · CEFR тесті емес',
    heuristicNotice: 'Бұл — жуық тілдік бағалау ғана; расталған CEFR немесе қауіпсіздік сараптамасы емес.',
    aiNeedsReview: 'ЖИ жасаған · тексеру қажет',
    curatedAnalysis: 'Дайындалған оқу талдауы',
    answerDevelopment: 'Жауаптың толықтығы',
    speechPrivacy: 'Қосымша · дауысты тану браузер қызметін қолдануы мүмкін',
    notRecommended: 'Сабаққа ұсынылмайды',
    demoData: 'ДЕМО ДЕРЕК',
  },
  ru: {
    nav: { home: 'Главная', discover: 'Каталог', library: 'Моё обучение', progress: 'Прогресс', research: 'Исследование' },
    hello: 'Добрый вечер, Амина',
    subtitle: 'Готова прокачать свой английский?',
    streak: '12 дней подряд',
    search: 'Поиск песни, исполнителя или навыка',
    continue: 'Продолжить обучение',
    resume: 'Продолжить урок',
    journey: 'Твой ритм, твой прогресс',
    journeySub: 'Ты развиваешь живой английский — песня за песней.',
    words: 'Слов изучено',
    minutes: 'Минут прослушано',
    accuracy: 'Точность тестов',
    lessons: 'Уроков завершено',
    weekly: 'Эта неделя',
    goal: 'Недельная цель',
    goalMeta: 'Завершено 3 из 5 уроков',
    recent: 'Новое из твоего плейлиста',
    viewAll: 'Смотреть все',
    featured: 'Английский специально для тебя',
    featuredSub: 'Уроки под твой уровень B1 и музыкальный вкус.',
    start: 'Начать урок',
    min: 'мин',
    exploreTitle: 'Найди свой следующий урок',
    exploreSub: 'Любимые песни превращаются в практику живого английского.',
    searchShort: 'Найти музыку',
    all: 'Все песни',
    safe: 'Для занятий',
    vocab: 'Лексика',
    idioms: 'Идиомы',
    listening: 'Аудирование',
    popular: 'Популярные уроки',
    selected: 'урок выбран',
    analyzeSong: 'Разобрать свою песню',
    analyzerTitle: 'Преврати любую песню в урок',
    analyzerSub: 'Добавь песню и небольшой фрагмент текста. SONORA оценит уровень, найдёт полезную лексику и создаст учебную карточку.',
    artistLabel: 'Исполнитель',
    songLabel: 'Название песни',
    lyricsLabel: 'Фрагмент текста',
    lyricsHint: 'Фрагмент отправляется только в настроенный AI-сервис SONORA и не сохраняется; краткая сводка анализа может быть сохранена.',
    runAnalysis: 'Проанализировать',
    analyzing: 'Ищем полезный английский…',
    analysisReady: 'Учебная карточка готова',
    detectedWords: 'Уникальных слов',
    slangFound: 'Найдено сленга',
    difficulty: 'Сложность',
    useForLesson: 'Использовать урок',
    libraryTitle: 'Моё обучение',
    librarySub: 'Сохраняй слова и выражения, которые хочешь сделать своими.',
    savedWords: 'Сохранённые слова',
    review: 'Повторить',
    progressTitle: 'Твой английский набирает ритм',
    progressSub: 'Смотри, что уже улучшается и что стоит практиковать дальше.',
    level: 'Текущий уровень',
    strongest: 'Сильный навык',
    focus: 'Следующий фокус',
    skillGrowth: 'Рост навыков',
    last30: 'Последние 30 дней',
    vocabulary: 'Словарный запас',
    comprehension: 'Аудирование',
    speaking: 'Говорение',
    grammar: 'Грамматика',
    back: 'Назад',
    lesson: 'Интерактивный урок',
    meaning: 'Смысл',
    vocabularyTab: 'Лексика',
    languageTab: 'Языковая лаборатория',
    practice: 'Практика',
    songMeaning: 'О чём эта песня на самом деле?',
    meaningLead: 'Понятное объяснение без перевода каждой строки.',
    keyIdea: 'Главная идея',
    mood: 'Настроение и посыл',
    culture: 'Важный контекст',
    learningMap: 'Карта урока',
    usefulWords: 'Полезных слов',
    expressions: 'Выражения',
    grammarPoints: 'Темы грамматики',
    understanding: 'Понимание песни',
    continueVocabulary: 'Перейти к словам',
    wordsFromSong: 'Слова, которые стоит запомнить',
    wordsSub: 'Пойми их здесь. Используй где угодно.',
    shouldLearn: 'Стоит ли это учить?',
    standard: 'Стандартный английский',
    informal: 'Разговорная речь',
    slang: 'Сленг',
    saveWord: 'Сохранить',
    saved: 'Сохранено',
    labTitle: 'Как работает живой английский',
    labSub: 'Узнай разницу между языком песен и формальным английским.',
    songForm: 'В песне / разговоре',
    classroomForm: 'Стандартная форма',
    why: 'Почему артисты так говорят',
    quizTitle: 'Проверим понимание',
    quizSub: 'Выбери значение, которое подходит контексту песни.',
    check: 'Проверить ответ',
    correct: 'Именно — ты правильно понял контекст.',
    retry: 'Почти. Обрати внимание на эмоциональный контекст и попробуй ещё раз.',
    finish: 'Завершить урок',
    complete: 'Урок завершён!',
    completeSub: 'Ты добавила 8 полезных слов и ещё одну песню в свой английский путь.',
    speakingTitle: 'Расскажи о песне',
    speakingPrompt: 'Какова главная идея песни и какие чувства она у тебя вызывает?',
    startSpeaking: 'Начать говорить',
    stopSpeaking: 'Слушаем…',
    speechUnsupported: 'Распознавание голоса недоступно в этом браузере. Можно напечатать ответ.',
    transcript: 'Твой ответ',
    speakingFeedback: 'Обратная связь',
    clarity: 'Понятность',
    vocabularyRange: 'Разнообразие слов',
    goHome: 'На главную',
    score: 'Учебная ценность',
    classroom: 'Для занятий',
    guided: 'С преподавателем',
    safeLabel: 'Подходит',
    wordsLower: 'слов',
    localAiTitle: 'MiniMax M3 · OpenRouter',
    localAiSidebar: 'Бесплатно создаёт уроки на трёх языках с одним web API-ключом.',
    openAnalyzer: 'Открыть анализатор',
    localAiReady: 'web AI готов',
    configuredAiReady: 'бесплатный web AI готов',
    localAiFallback: 'Web AI недоступен — доступна только базовая оценка',
    checkingAi: 'Проверяем настройку web AI…',
    basicLocalAnalysis: 'Базовая эвристика · не оценка CEFR',
    heuristicNotice: 'Это приблизительная языковая оценка, а не подтверждённая оценка CEFR или безопасности.',
    aiNeedsReview: 'Создано AI · требуется проверка',
    curatedAnalysis: 'Подготовленный учебный разбор',
    answerDevelopment: 'Развёрнутость ответа',
    speechPrivacy: 'Необязательно · распознавание может использовать сервис браузера',
    notRecommended: 'Не для занятий',
    demoData: 'ДЕМО-ДАННЫЕ',
  },
};

export const songs = [
  { id: 'lovely', title: 'lovely', artist: 'Billie Eilish & Khalid', level: 'B1', minutes: 18, score: 92, safety: 'guided', cover: 'cover-violet', genre: 'Alternative pop', tags: ['Vocabulary', 'Metaphors', 'Speaking'], progress: 48, media: { provider: 'youtube', videoId: 'V1Pl8CzNzCw', kind: 'official_video', official: true, channelLabel: 'Billie Eilish', verifiedAt: '2026-09-05' } },
  { id: 'counting-stars', title: 'Counting Stars', artist: 'OneRepublic', level: 'B1', minutes: 16, score: 89, safety: 'safe', cover: 'cover-amber', genre: 'Pop rock', tags: ['Idioms', 'Listening', 'Grammar'], media: { provider: 'youtube', videoId: 'hT_nvWreIhg', kind: 'official_video', official: true, channelLabel: 'OneRepublic', verifiedAt: '2026-09-05' } },
  { id: 'flowers', title: 'Flowers', artist: 'Miley Cyrus', level: 'A2–B1', minutes: 14, score: 87, safety: 'safe', cover: 'cover-coral', genre: 'Pop', tags: ['Vocabulary', 'Self-care', 'Can / could'], media: { provider: 'youtube', videoId: 'G7KNmW9a75Y', kind: 'official_video', official: true, channelLabel: 'Miley Cyrus', verifiedAt: '2026-09-05' } },
  { id: 'believer', title: 'Believer', artist: 'Imagine Dragons', level: 'B1–B2', minutes: 20, score: 90, safety: 'safe', cover: 'cover-lime', genre: 'Pop rock', tags: ['Word stress', 'Metaphors', 'Past tense'], media: { provider: 'youtube', videoId: '7wtfhZwyrcc', kind: 'official_video', official: true, channelLabel: 'Imagine Dragons', verifiedAt: '2026-09-05' } },
  { id: 'blinding-lights', title: 'Blinding Lights', artist: 'The Weeknd', level: 'B1', minutes: 17, score: 86, safety: 'guided', cover: 'cover-red', genre: 'Synth-pop', tags: ['Listening', 'Phrasal verbs', 'Pronunciation'], media: { provider: 'youtube', videoId: '4NRXx6U8ABQ', kind: 'official_video', official: true, channelLabel: 'The Weeknd', verifiedAt: '2026-09-05' } },
  { id: 'someone-you-loved', title: 'Someone You Loved', artist: 'Lewis Capaldi', level: 'B1', minutes: 15, score: 91, safety: 'safe', cover: 'cover-blue', genre: 'Pop ballad', tags: ['Emotions', 'Past forms', 'Speaking'], media: { provider: 'youtube', videoId: 'zABLecsR5UE', kind: 'official_video', official: true, channelLabel: 'Lewis Capaldi', verifiedAt: '2026-09-05' } },
];

export const lovelyLesson = {
  meaning: {
    en: {
      idea: 'The song explores the feeling of being trapped in loneliness while still hoping that someone will understand and stay.',
      mood: 'Quiet, vulnerable and emotionally tense. The contrast between a gentle sound and heavy emotions makes the message stronger.',
      culture: 'In English pop music, physical images such as walls, glass or a home often represent emotional states rather than real places.',
    },
    kk: {
      idea: 'Ән жалғыздықтың құрсауында қалған адамның күйін және оны біреу түсініп, жанында қалады деген үмітін сипаттайды.',
      mood: 'Тыныш, осал әрі эмоциялық тұрғыдан шиеленісті. Жұмсақ әуен мен ауыр сезімдердің қарама-қайшылығы ойды күшейтеді.',
      culture: 'Ағылшын поп-музыкасында қабырға, әйнек немесе үй сияқты физикалық бейнелер көбіне нақты орынды емес, адамның ішкі күйін білдіреді.',
    },
    ru: {
      idea: 'Песня передаёт ощущение человека, застрявшего в одиночестве, который всё ещё надеется, что кто-то его поймёт и останется рядом.',
      mood: 'Тихое, уязвимое и эмоционально напряжённое. Контраст мягкого звучания и тяжёлых чувств усиливает посыл.',
      culture: 'В англоязычной поп-музыке стены, стекло или дом часто обозначают внутреннее состояние, а не реальные места.',
    },
  },
  words: [
    { word: 'lovely', ipa: '/ˈlʌv.li/', cefr: 'A2', type: 'standard', meaning: { en: 'pleasant or beautiful', kk: 'сүйкімді, тамаша', ru: 'прекрасный, милый' }, example: 'What a lovely way to start the day.' },
    { word: 'alone', ipa: '/əˈləʊn/', cefr: 'A2', type: 'standard', meaning: { en: 'without other people', kk: 'жалғыз', ru: 'один, в одиночестве' }, example: 'She enjoys being alone, but not feeling lonely.' },
    { word: 'fragile', ipa: '/ˈfrædʒ.aɪl/', cefr: 'B2', type: 'standard', meaning: { en: 'easily broken or emotionally hurt', kk: 'нәзік, осал', ru: 'хрупкий, уязвимый' }, example: 'Trust can feel fragile after an argument.' },
    { word: 'shatter', ipa: '/ˈʃæt.ər/', cefr: 'B2', type: 'standard', meaning: { en: 'to break suddenly into many pieces', kk: 'күл-талқан ету', ru: 'разбить вдребезги' }, example: 'The news shattered all of his expectations.' },
    { word: 'escape', ipa: '/ɪˈskeɪp/', cefr: 'B1', type: 'standard', meaning: { en: 'to get away from a difficult place or feeling', kk: 'қашып құтылу', ru: 'вырваться, избежать' }, example: 'Music helps me escape from daily stress.' },
    { word: 'wanna', ipa: '/ˈwɒn.ə/', cefr: 'B1', type: 'informal', meaning: { en: 'spoken form of “want to”', kk: 'want to тіркесінің ауызекі түрі', ru: 'разговорная форма “want to”' }, example: 'I wanna learn how native speakers really talk.' },
  ],
  languageLab: [
    { song: 'wanna', standard: 'want to', note: { en: 'It matches natural fast speech and the rhythm. Avoid it in formal writing.', kk: 'Жылдам сөйлеуге және ырғаққа сәйкес келеді. Ресми жазуда қолданбаған дұрыс.', ru: 'Форма соответствует быстрой речи и ритму. В официальном письме её лучше избегать.' } },
    { song: 'gotta', standard: 'have got to / have to', note: { en: 'A common spoken reduction used for urgency or necessity.', kk: 'Шұғылдықты немесе қажеттілікті білдіретін кең таралған ауызекі қысқарту.', ru: 'Распространённое разговорное сокращение для выражения срочности или необходимости.' } },
    { song: "ain't", standard: 'am not / is not / are not / have not', note: { en: 'A non-standard form used in dialects, casual speech and music. Understand it; use it carefully.', kk: 'Диалектілерде, бейресми сөйлеуде және музыкада кездесетін стандартты емес форма. Түсінген жөн, қолданғанда абай бол.', ru: 'Нестандартная форма из диалектов, разговорной речи и музыки. Понимать стоит, употреблять — осторожно.' } },
  ],
  quiz: {
    question: {
      en: 'In this song, what does the idea of a “glass home” most likely represent?',
      kk: 'Бұл әндегі «әйнек үй» бейнесі нені білдіруі мүмкін?',
      ru: 'Что, скорее всего, означает образ «стеклянного дома» в этой песне?',
    },
    answers: {
      en: ['An expensive modern house', 'Feeling visible, fragile and unable to hide', 'A place where the singer grew up'],
      kk: ['Қымбат заманауи үй', 'Өзін осал, қорғансыз және жасырына алмайтындай сезіну', 'Әншінің өскен жері'],
      ru: ['Дорогой современный дом', 'Ощущение уязвимости, открытости и невозможности спрятаться', 'Место, где вырос исполнитель'],
    },
    correct: 1,
  },
};

const countingStarsLesson = {
  meaning: {
    en: { idea: 'The song contrasts chasing money with chasing dreams, asking whether success should be measured by wealth or by a meaningful life.', mood: 'Energetic and hopeful, but also restless. The fast rhythm mirrors a mind full of ambition and doubt.', culture: '“Counting stars” works as a metaphor for imagination and purpose, while money represents social expectations.' },
    kk: { idea: 'Ән ақша табу мен арман қуу арасындағы таңдауды көрсетіп, жетістік байлықпен бе, әлде мәнді өмірмен өлшене ме деген сұрақ қояды.', mood: 'Қуатты әрі үмітті, бірақ мазасыз. Жылдам ырғақ амбиция мен күмәнге толы ойды бейнелейді.', culture: '«Жұлдыздарды санау» қиял мен өмірлік мақсаттың метафорасы, ал ақша — қоғамның күтулерін білдіреді.' },
    ru: { idea: 'Песня противопоставляет погоню за деньгами и мечтой, задавая вопрос: измеряется ли успех богатством или осмысленной жизнью.', mood: 'Энергичное и вдохновляющее, но беспокойное. Быстрый ритм передаёт амбиции и внутренние сомнения.', culture: '«Считать звёзды» — метафора мечты и смысла, а деньги обозначают ожидания общества.' },
  },
  words: [
    { word: 'count', ipa: '/kaʊnt/', cefr: 'A2', type: 'standard', meaning: { en: 'to calculate how many there are', kk: 'санау', ru: 'считать' }, example: 'Do not count the hours; make the hours count.' },
    { word: 'dream', ipa: '/driːm/', cefr: 'A2', type: 'standard', meaning: { en: 'a strong hope for the future', kk: 'арман', ru: 'мечта' }, example: 'Her dream is to study music abroad.' },
    { word: 'seek', ipa: '/siːk/', cefr: 'B2', type: 'standard', meaning: { en: 'to try to find or achieve something', kk: 'іздеу, ұмтылу', ru: 'искать, стремиться' }, example: 'Many people seek a sense of purpose.' },
    { word: 'bold', ipa: '/bəʊld/', cefr: 'B1', type: 'standard', meaning: { en: 'brave and confident', kk: 'батыл', ru: 'смелый' }, example: 'It was a bold decision to follow his dream.' },
    { word: 'burn', ipa: '/bɜːn/', cefr: 'A2', type: 'standard', meaning: { en: 'to be damaged by fire; metaphorically, to use up', kk: 'жану; ауыспалы мағынада жұмсау', ru: 'гореть; образно — тратить' }, example: 'Do not burn all your energy at once.' },
    { word: 'lately', ipa: '/ˈleɪt.li/', cefr: 'B1', type: 'standard', meaning: { en: 'recently', kk: 'соңғы кездері', ru: 'в последнее время' }, example: 'I have been listening to more podcasts lately.' },
  ],
  languageLab: [
    { song: 'I have been thinking', standard: 'present perfect continuous', note: { en: 'Use it for an activity that started earlier and is still relevant now.', kk: 'Бұрын басталып, қазір де маңызды әрекет үшін қолданылады.', ru: 'Используется для действия, которое началось раньше и всё ещё актуально.' } },
    { song: 'counting stars', standard: 'thinking about dreams', note: { en: 'A concrete image replaces an abstract idea and makes it memorable.', kk: 'Нақты бейне абстрактілі ойды алмастырып, оны есте қаларлық етеді.', ru: 'Конкретный образ заменяет абстрактную идею и делает её запоминающейся.' } },
    { song: 'lose sleep', standard: 'worry about something', note: { en: 'This idiom means that a concern is keeping you awake or anxious.', kk: 'Бұл идиома бір нәрсеге қатты алаңдауды білдіреді.', ru: 'Идиома означает сильно переживать из-за чего-либо.' } },
  ],
  quiz: { question: { en: 'What does “counting stars” mainly represent?', kk: '«Жұлдыздарды санау» негізінен нені білдіреді?', ru: 'Что главным образом означает «считать звёзды»?' }, answers: { en: ['Learning astronomy', 'Choosing dreams and meaning over money', 'Being unable to sleep'], kk: ['Астрономияны үйрену', 'Ақшадан гөрі арман мен мағынаны таңдау', 'Ұйықтай алмау'], ru: ['Изучение астрономии', 'Выбор мечты и смысла вместо денег', 'Неспособность заснуть'] }, correct: 1 },
};

const flowersLesson = {
  meaning: {
    en: { idea: 'The song is about rebuilding confidence after a relationship and learning to give yourself the care you once expected from someone else.', mood: 'Confident, calm and celebratory. Independence is presented as growth rather than revenge.', culture: 'Buying flowers is traditionally a romantic gesture; here it becomes a symbol of self-respect and independence.' },
    kk: { idea: 'Ән қарым-қатынастан кейін өзіне деген сенімді қайта құру және бұрын өзгеден күткен қамқорлықты өзіңе көрсетуді үйрену туралы.', mood: 'Сенімді, сабырлы әрі көтеріңкі. Тәуелсіздік кек емес, өсу ретінде беріледі.', culture: 'Гүл сыйлау дәстүрлі түрде романтикалық ишара, ал бұл жерде ол өзін құрметтеу мен тәуелсіздіктің белгісі.' },
    ru: { idea: 'Песня о восстановлении уверенности после отношений и умении дать себе ту заботу, которую раньше ожидал от другого человека.', mood: 'Уверенное, спокойное и праздничное. Независимость показана как развитие, а не месть.', culture: 'Покупка цветов традиционно считается романтическим жестом; здесь она становится символом самоуважения.' },
  },
  words: [
    { word: 'independent', ipa: '/ˌɪn.dɪˈpen.dənt/', cefr: 'B1', type: 'standard', meaning: { en: 'able to manage without another person', kk: 'тәуелсіз', ru: 'независимый' }, example: 'Learning to travel alone made her more independent.' },
    { word: 'regret', ipa: '/rɪˈɡret/', cefr: 'B1', type: 'standard', meaning: { en: 'sadness about a past decision', kk: 'өкініш', ru: 'сожаление' }, example: 'He does not regret choosing a new direction.' },
    { word: 'forgive', ipa: '/fəˈɡɪv/', cefr: 'B1', type: 'standard', meaning: { en: 'to stop feeling angry with someone', kk: 'кешіру', ru: 'простить' }, example: 'It can take time to forgive and move forward.' },
    { word: 'hold hands', ipa: '/həʊld hændz/', cefr: 'A2', type: 'standard', meaning: { en: 'to take another person’s hand', kk: 'қол ұстасу', ru: 'держаться за руки' }, example: 'The children held hands while crossing the road.' },
    { word: 'self-worth', ipa: '/ˌselfˈwɜːθ/', cefr: 'B2', type: 'standard', meaning: { en: 'the sense that you have value', kk: 'өзіндік құндылық', ru: 'чувство собственной ценности' }, example: 'Your self-worth should not depend on likes.' },
    { word: 'better', ipa: '/ˈbet.ər/', cefr: 'A1', type: 'standard', meaning: { en: 'of a higher quality or in an improved state', kk: 'жақсырақ', ru: 'лучше' }, example: 'She feels better after getting some rest.' },
  ],
  languageLab: [
    { song: 'I can buy', standard: 'can + base verb', note: { en: '“Can” expresses ability. The verb after it stays in the base form.', kk: 'Can қабілетті білдіреді. Одан кейін етістіктің негізгі түрі қолданылады.', ru: 'Can выражает способность. После него используется начальная форма глагола.' } },
    { song: 'love me better', standard: 'take better care of myself', note: { en: 'The short expression carries the wider idea of self-respect and care.', kk: 'Қысқа тіркес өзін құрметтеу мен қамқорлық идеясын береді.', ru: 'Короткое выражение передаёт более широкую идею заботы о себе.' } },
    { song: 'no remorse', standard: 'without regret', note: { en: '“Remorse” is a stronger, more emotional synonym for regret.', kk: 'Remorse — regret сөзінің эмоциясы күштірек синонимі.', ru: 'Remorse — более сильный и эмоциональный синоним regret.' } },
  ],
  quiz: { question: { en: 'Why are flowers important in the song?', kk: 'Әндегі гүлдердің маңызы неде?', ru: 'Почему цветы важны в песне?' }, answers: { en: ['They represent self-care and independence', 'The singer wants to become a florist', 'They describe a garden'], kk: ['Олар өзін күту мен тәуелсіздікті білдіреді', 'Әнші гүл сатушы болғысы келеді', 'Олар бақты сипаттайды'], ru: ['Они обозначают заботу о себе и независимость', 'Исполнитель хочет стать флористом', 'Они описывают сад'] }, correct: 0 },
};

const believerLesson = {
  meaning: {
    en: { idea: 'The song presents pain and difficulty as forces that can shape a stronger, more determined person.', mood: 'Intense, defiant and motivating. Repetition makes the central transformation feel powerful.', culture: 'English motivational music often uses physical pain as a metaphor for emotional struggle and personal growth.' },
    kk: { idea: 'Ән ауырсыну мен қиындықты адамды күштірек әрі табанды ететін күш ретінде көрсетеді.', mood: 'Қарқынды, қайсар және мотивациялық. Қайталау негізгі өзгерісті қуатты етеді.', culture: 'Ағылшын мотивациялық музыкасында физикалық ауырсыну эмоциялық күрес пен тұлғалық өсудің метафорасы ретінде жиі қолданылады.' },
    ru: { idea: 'Песня показывает боль и трудности как силу, способную сформировать более стойкого и решительного человека.', mood: 'Напряжённое, дерзкое и мотивирующее. Повтор усиливает ощущение внутреннего преобразования.', culture: 'В англоязычной мотивирующей музыке физическая боль часто служит метафорой эмоциональной борьбы и роста.' },
  },
  words: [
    { word: 'believer', ipa: '/bɪˈliː.vər/', cefr: 'B1', type: 'standard', meaning: { en: 'someone who accepts an idea as true', kk: 'сенуші адам', ru: 'тот, кто верит' }, example: 'She is a firm believer in daily practice.' },
    { word: 'pain', ipa: '/peɪn/', cefr: 'A2', type: 'standard', meaning: { en: 'physical or emotional suffering', kk: 'ауырсыну', ru: 'боль' }, example: 'He turned the pain of failure into motivation.' },
    { word: 'strength', ipa: '/streŋθ/', cefr: 'B1', type: 'standard', meaning: { en: 'the ability to deal with difficulty', kk: 'күш, төзімділік', ru: 'сила, стойкость' }, example: 'Asking for help can be a sign of strength.' },
    { word: 'determined', ipa: '/dɪˈtɜː.mɪnd/', cefr: 'B1', type: 'standard', meaning: { en: 'not willing to give up', kk: 'табандылық танытқан', ru: 'решительный' }, example: 'They were determined to finish the project.' },
    { word: 'break down', ipa: '/breɪk daʊn/', cefr: 'B1', type: 'informal', meaning: { en: 'to lose emotional control', kk: 'эмоциялық күйзеліске түсу', ru: 'эмоционально сломаться' }, example: 'It is normal to break down after extreme stress.' },
    { word: 'rise', ipa: '/raɪz/', cefr: 'B1', type: 'standard', meaning: { en: 'to move upward or become stronger', kk: 'көтерілу', ru: 'подниматься' }, example: 'Confidence can rise with regular practice.' },
  ],
  languageLab: [
    { song: 'pain made me', standard: 'make + object + base verb', note: { en: 'This structure explains that something caused a change or action.', kk: 'Бұл құрылым бір нәрсенің өзгеріске немесе әрекетке себеп болғанын білдіреді.', ru: 'Эта конструкция показывает, что что-то вызвало изменение или действие.' } },
    { song: 'fire in my veins', standard: 'strong energy inside me', note: { en: 'A physical image makes determination feel immediate and intense.', kk: 'Физикалық бейне табандылықты айқын және күшті көрсетеді.', ru: 'Физический образ делает решимость яркой и сильной.' } },
    { song: 'break me down', standard: 'make me lose confidence', note: { en: 'This phrasal verb is often used for emotional pressure, not physical damage.', kk: 'Бұл фразалық етістік физикалық емес, эмоциялық қысымды білдіреді.', ru: 'Этот фразовый глагол часто обозначает эмоциональное давление, а не физический вред.' } },
  ],
  quiz: { question: { en: 'How is pain presented in the song?', kk: 'Әнде ауырсыну қалай көрсетілген?', ru: 'Как в песне представлена боль?' }, answers: { en: ['Only as something negative', 'As a source of strength and transformation', 'As a medical problem'], kk: ['Тек жағымсыз нәрсе ретінде', 'Күш пен өзгерістің көзі ретінде', 'Медициналық мәселе ретінде'], ru: ['Только как нечто отрицательное', 'Как источник силы и преобразования', 'Как медицинская проблема'] }, correct: 1 },
};

const blindingLightsLesson = {
  meaning: {
    en: { idea: 'The song combines loneliness, late-night city energy and a strong desire to reconnect with someone important.', mood: 'Fast and euphoric on the surface, but emotionally lonely underneath.', culture: 'Bright city lights are used ironically: the world looks exciting, yet the narrator still feels lost without connection.' },
    kk: { idea: 'Ән жалғыздықты, түнгі қаланың қуатын және маңызды адаммен қайта байланысуға деген күшті қалауды біріктіреді.', mood: 'Сырттай жылдам әрі шаттыққа толы, бірақ ішінде жалғыздық сезіледі.', culture: 'Қаланың жарықтары ирониямен қолданылады: әлем қызықты көрінгенмен, кейіпкер жақын адамсыз өзін жоғалғандай сезінеді.' },
    ru: { idea: 'Песня соединяет одиночество, энергию ночного города и сильное желание вновь быть рядом с важным человеком.', mood: 'Быстрое и эйфоричное снаружи, но внутренне одинокое.', culture: 'Яркие огни города используются иронично: мир кажется захватывающим, но герой всё равно потерян без близости.' },
  },
  words: [
    { word: 'blinding', ipa: '/ˈblaɪn.dɪŋ/', cefr: 'B2', type: 'standard', meaning: { en: 'extremely bright; making it hard to see', kk: 'көз қарықтыратын', ru: 'ослепительный' }, example: 'The blinding sunlight reflected off the snow.' },
    { word: 'withdrawal', ipa: '/wɪðˈdrɔː.əl/', cefr: 'C1', type: 'standard', meaning: { en: 'an unpleasant feeling when something familiar is missing', kk: 'әдеттегі нәрсе болмағанда туатын күй', ru: 'неприятное состояние из-за отсутствия привычного' }, example: 'He joked about having phone withdrawal.' },
    { word: 'touch', ipa: '/tʌtʃ/', cefr: 'A2', type: 'standard', meaning: { en: 'physical contact; also emotional connection', kk: 'жанасу; эмоциялық байланыс', ru: 'прикосновение; эмоциональная связь' }, example: 'A thoughtful message added a personal touch.' },
    { word: 'run out of', ipa: '/rʌn aʊt əv/', cefr: 'B1', type: 'informal', meaning: { en: 'to have no more of something', kk: 'бір нәрсе таусылу', ru: 'исчерпать, остаться без' }, example: 'We ran out of time before the final question.' },
    { word: 'drown', ipa: '/draʊn/', cefr: 'B2', type: 'standard', meaning: { en: 'to be overwhelmed by water or, metaphorically, emotion', kk: 'бату; сезімге тұншығу', ru: 'тонуть; захлёбываться эмоциями' }, example: 'Do not drown in details; focus on the main idea.' },
    { word: 'on my own', ipa: '/ɒn maɪ əʊn/', cefr: 'B1', type: 'informal', meaning: { en: 'alone or without help', kk: 'өз бетімше, жалғыз', ru: 'самостоятельно, один' }, example: 'I solved the problem on my own.' },
  ],
  languageLab: [
    { song: 'run out of time', standard: 'have no time left', note: { en: 'A very common phrasal expression for using all of a limited resource.', kk: 'Шектеулі ресурс толық біткенде қолданылатын кең таралған тіркес.', ru: 'Очень распространённое выражение об исчерпании ограниченного ресурса.' } },
    { song: 'blinded by the lights', standard: 'overwhelmed by the city', note: { en: '“Blinded” is metaphorical: the environment is intense and disorienting.', kk: 'Blinded ауыспалы мағынада: орта тым қарқынды әрі бағдардан жаңылдырады.', ru: 'Blinded используется образно: окружение слишком яркое и дезориентирует.' } },
    { song: 'on my own', standard: 'alone / independently', note: { en: 'The exact meaning depends on whether the context emphasizes loneliness or ability.', kk: 'Мағынасы контекстегі жалғыздыққа немесе дербестікке байланысты.', ru: 'Значение зависит от того, подчёркивает контекст одиночество или самостоятельность.' } },
  ],
  quiz: { question: { en: 'Why is the title emotionally ironic?', kk: 'Неліктен ән атауында эмоциялық ирония бар?', ru: 'Почему название песни эмоционально иронично?' }, answers: { en: ['The city is bright, but the narrator feels lost and lonely', 'The narrator dislikes electricity', 'The song takes place during the day'], kk: ['Қала жарық, бірақ кейіпкер өзін жалғыз әрі адасқандай сезінеді', 'Кейіпкер электр қуатын ұнатпайды', 'Ән күндіз өтеді'], ru: ['Город яркий, но герой чувствует себя потерянным и одиноким', 'Герой не любит электричество', 'Действие происходит днём'] }, correct: 0 },
};

const someoneYouLovedLesson = {
  meaning: {
    en: { idea: 'The song describes the shock of losing emotional support and having to face daily life without the person who once made it feel safer.', mood: 'Open, grieving and deeply vulnerable. Simple language makes the emotion direct and relatable.', culture: 'English uses many physical idioms—guard, rug, fall—to explain trust and emotional security.' },
    kk: { idea: 'Ән эмоциялық тіректі жоғалтудың ауырлығын және өмірді бұрын қауіпсіздік сыйлаған адамсыз жалғастыруды сипаттайды.', mood: 'Ашық, мұңды және өте осал. Қарапайым тіл эмоцияны тікелей әрі түсінікті етеді.', culture: 'Ағылшын тілінде сенім мен эмоциялық қауіпсіздікті түсіндіру үшін guard, rug, fall сияқты физикалық идиомалар көп қолданылады.' },
    ru: { idea: 'Песня описывает потрясение от потери эмоциональной опоры и необходимость жить без человека, рядом с которым было безопаснее.', mood: 'Открытое, скорбящее и очень уязвимое. Простая лексика делает эмоцию прямой и понятной.', culture: 'В английском много физических идиом — guard, rug, fall — для описания доверия и эмоциональной безопасности.' },
  },
  words: [
    { word: 'guard', ipa: '/ɡɑːd/', cefr: 'B1', type: 'standard', meaning: { en: 'protection against danger or emotional hurt', kk: 'қорғаныс', ru: 'защита' }, example: 'It took time for him to let his guard down.' },
    { word: 'numb', ipa: '/nʌm/', cefr: 'B2', type: 'standard', meaning: { en: 'unable to feel physically or emotionally', kk: 'сезімсіз, жансызданған', ru: 'онемевший, бесчувственный' }, example: 'She felt numb after hearing the unexpected news.' },
    { word: 'heal', ipa: '/hiːl/', cefr: 'B1', type: 'standard', meaning: { en: 'to become healthy or emotionally well again', kk: 'жазылу, қалпына келу', ru: 'исцеляться, восстанавливаться' }, example: 'Talking can help emotional wounds heal.' },
    { word: 'pull the rug', ipa: '/pʊl ðə rʌɡ/', cefr: 'C1', type: 'informal', meaning: { en: 'to suddenly remove support or security', kk: 'кенеттен қолдаусыз қалдыру', ru: 'внезапно лишить поддержки' }, example: 'The cancelled funding pulled the rug from under the team.' },
    { word: 'get through', ipa: '/ɡet θruː/', cefr: 'B1', type: 'informal', meaning: { en: 'to survive or finish something difficult', kk: 'қиындықты еңсеру', ru: 'пережить, справиться' }, example: 'Friends helped me get through a difficult week.' },
    { word: 'safe', ipa: '/seɪf/', cefr: 'A2', type: 'standard', meaning: { en: 'protected from danger or harm', kk: 'қауіпсіз', ru: 'в безопасности' }, example: 'A good classroom should feel safe for questions.' },
  ],
  languageLab: [
    { song: 'let my guard down', standard: 'allow myself to trust', note: { en: 'This idiom comes from physical defence but usually describes emotional openness.', kk: 'Идиома физикалық қорғаныстан шыққанымен, эмоциялық ашықтықты білдіреді.', ru: 'Идиома происходит из физической защиты, но обычно означает эмоциональную открытость.' } },
    { song: 'pull the rug', standard: 'remove support suddenly', note: { en: 'Imagine losing the surface under your feet: the idiom emphasizes shock.', kk: 'Аяқ астындағы тіректен айырылуды елестет: идиома күтпеген соққыны көрсетеді.', ru: 'Представьте, что опора исчезает из-под ног: идиома подчёркивает внезапность.' } },
    { song: 'get through the day', standard: 'manage to finish the day', note: { en: '“Get through” focuses on surviving a difficult experience.', kk: 'Get through қиын тәжірибені еңсеруге назар аударады.', ru: 'Get through подчёркивает преодоление трудного опыта.' } },
  ],
  quiz: { question: { en: 'What does “let my guard down” mean emotionally?', kk: 'Эмоциялық тұрғыдан «let my guard down» нені білдіреді?', ru: 'Что эмоционально означает «let my guard down»?' }, answers: { en: ['Stop working as a security guard', 'Allow yourself to trust and be vulnerable', 'Become less physically strong'], kk: ['Күзетші болып жұмыс істеуді тоқтату', 'Сенуге және осал болуға мүмкіндік беру', 'Физикалық тұрғыдан әлсіреу'], ru: ['Перестать работать охранником', 'Позволить себе доверять и быть уязвимым', 'Стать физически слабее'] }, correct: 1 },
};

export const lessons = {
  lovely: lovelyLesson,
  'counting-stars': countingStarsLesson,
  flowers: flowersLesson,
  believer: believerLesson,
  'blinding-lights': blindingLightsLesson,
  'someone-you-loved': someoneYouLovedLesson,
};
